/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class panelJugador extends javax.swing.JPanel {

    /**
     * Creates new form panelJugador
     */
    public panelJugador(Modelo.Jugador jugador) {
        initComponents();
        
        jTextField2.setText(jugador.getNombre());
        jTextField4.setText(jugador.getNumIdentificacion());
        jTextField1.setText(String.valueOf(jugador.getEdad()));
        jTextField5.setText(String.valueOf(jugador.getPosicion()));
        jTextField3.setText(String.valueOf(jugador.getPromedioBateo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(50, 50, 50));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("NOMBRE");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField2.setOpaque(true);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(50, 50, 50));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("IDENTIFICACION");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField4.setOpaque(true);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 180, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(50, 50, 50));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("EDAD");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField1.setOpaque(true);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(50, 50, 50));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("POSICION");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField5.setOpaque(true);
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 30));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(50, 50, 50));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("PROMEDIO DE BATEO");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField3.setOpaque(true);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
