/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class VistaReportes extends javax.swing.JDialog {

    /**
     * Creates new form VistaReportes
     *
     * @param parent
     * @param equipo
     */
    public VistaReportes(java.awt.Frame parent, Modelo.EquipoDeBeisbol equipo) {
        super(parent, true);
        initComponents();

        int numeroLanzadores9a12 = 0, numeroLanzadores13a16 = 0
                ,cantLanzadores = 0,cantReceptores = 0,cantPrimeraBase = 0,cantSegundoBase = 0, cantShortstop=0,cantJardinero = 0;
        
        float promLanzadores = 0,promReceptores = 0,promPrimeraBase = 0,promSegundoBase = 0, promShortstop=0,promJardinero = 0;

        Modelo.Nodo cabeza = equipo.getLista().getCabeza(), promedioBajo = cabeza;
        while (cabeza != null) {

            if (cabeza.getJugador().getEdad() <= 12 && cabeza.getJugador().getEdad() >= 9) {
                jPanel3.add(new panelJugador(cabeza.getJugador()));
                if (cabeza.getJugador().getPosicion() == Modelo.Posicion.LANZADOR) {
                    numeroLanzadores9a12++;
                }
            } else if (cabeza.getJugador().getEdad() <= 16 && cabeza.getJugador().getEdad() >= 13 && (cabeza.getJugador().getPosicion() == Modelo.Posicion.LANZADOR)) {
                numeroLanzadores13a16++;
            }

            if (cabeza.getJugador().getPromedioBateo() < promedioBajo.getJugador().getPromedioBateo()) {
                promedioBajo = cabeza;
            }
            
            if(null != cabeza.getJugador().getPosicion())switch (cabeza.getJugador().getPosicion()) {
                case JARDINERO:
                    promJardinero+=cabeza.getJugador().getPromedioBateo();
                    cantJardinero++;
                    break;
                case LANZADOR:
                    promLanzadores+=cabeza.getJugador().getPromedioBateo();
                    cantLanzadores++;
                    break;
                case PRIMERA_BASE:
                    promPrimeraBase+=cabeza.getJugador().getPromedioBateo();
                    cantPrimeraBase++;
                    break;
                case RECEPTOR:
                    promReceptores+=cabeza.getJugador().getPromedioBateo();
                    cantReceptores++;
                    break;
                case SEGUNDA_BASE:
                    promSegundoBase+=cabeza.getJugador().getPromedioBateo();
                    cantSegundoBase++;
                    break;
                case SHORTSTOP:
                    promShortstop+=cabeza.getJugador().getPromedioBateo();
                    cantShortstop++;
                    break;
                default:
                    break;
            }
            
            cabeza = cabeza.getSiguienteNodo();
        }
        
        this.jLabel16.setText(String.valueOf(promLanzadores/cantLanzadores));
        this.jLabel17.setText(String.valueOf(promReceptores/cantReceptores));
        this.jLabel18.setText(String.valueOf(promShortstop/cantShortstop));
        this.jLabel19.setText(String.valueOf(promJardinero/cantJardinero));
        this.jLabel20.setText(String.valueOf(promPrimeraBase/cantPrimeraBase));
        this.jLabel15.setText(String.valueOf(promSegundoBase/cantSegundoBase));
        

        jLabel5.setText(String.valueOf(numeroLanzadores9a12));
        jLabel7.setText(String.valueOf(numeroLanzadores13a16));

        jLabel4.setText(promedioBajo.getJugador().toString());

        for (int i = 0; i < 9; i++) {
            javax.swing.JPanel panel = new javax.swing.JPanel();
            panel.setBackground(new java.awt.Color(35, 35, 35));
            this.jPanel3.add(panel);
        }

        this.jPanel3.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(35, 35, 35));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("NOMBRE");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField2.setOpaque(true);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(35, 35, 35));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("EDAD");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField1.setOpaque(true);
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(35, 35, 35));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("POSICION");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField5.setOpaque(true);
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 30));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(35, 35, 35));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("PROMEDIO DE BATEO");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField3.setOpaque(true);
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 30));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(35, 35, 35));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("IDENTIFICACION");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField4.setOpaque(true);
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 180, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JUGADORES 9-12 AÑOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(35, 35, 35));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, 220));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEGUNDA BASE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pitchers o lanzadores que tiene el equipo con edades desde los 9 a los 12 años : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 340, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 110, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pitchers o lanzadores que tiene el equipo con edades desde los 13 a los 16 años : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 110, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jugador con menor promedio de bateo del equipo : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edad promedio de los jugadores, para cada una de las posiciones.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LANZADOR: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RECEPTOR: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SHORTSTOP:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JARDINERO: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRIMERA BASE: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("0");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 240, -1));

        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("0");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, -1));

        jLabel17.setForeground(new java.awt.Color(255, 153, 153));
        jLabel17.setText("0");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 180, -1));

        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("0");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 180, -1));

        jLabel19.setForeground(new java.awt.Color(255, 153, 153));
        jLabel19.setText("0");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 180, -1));

        jLabel20.setForeground(new java.awt.Color(255, 153, 153));
        jLabel20.setText("0");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
