/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class Vista extends javax.swing.JFrame {

    private Modelo.EquipoDeBeisbol equipo;

    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.equipo = new Modelo.EquipoDeBeisbol();

    }

    public void actualizarTabla(Modelo.ListaEnlazadaSimple lista) {

        this.jPanel3.removeAll();

        Modelo.Nodo temporal = lista.getCabeza();

        while (temporal != null) {
            this.jPanel3.add(new panelJugador(temporal.getJugador()));
            temporal = temporal.getSiguienteNodo();
        }

        for (int i = 0; i < 15; i++) {
            javax.swing.JPanel panel = new javax.swing.JPanel();
            panel.setBackground(new java.awt.Color(35, 35, 35));
            this.jPanel3.add(panel);
        }

        this.jPanel3.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(35, 35, 35));
        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, 40));

        jButton2.setBackground(new java.awt.Color(35, 35, 35));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REPORTES");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 40));

        jComboBox1.setBackground(new java.awt.Color(35, 35, 35));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Promedio de bateo" }));
        jComboBox1.setBorder(null);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar por nombre o identificacion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organizar por");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 90, 20));

        jTextField6.setBackground(new java.awt.Color(35, 35, 35));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, 30));

        jButton3.setBackground(new java.awt.Color(35, 35, 35));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Buscar");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 70, 30));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 40, 10));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(35, 35, 35));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("NOMBRE");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField2.setOpaque(true);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(35, 35, 35));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("IDENTIFICACION");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField4.setOpaque(true);
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 180, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(35, 35, 35));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("EDAD");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField1.setOpaque(true);
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(35, 35, 35));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("POSICION");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField5.setOpaque(true);
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 30));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(35, 35, 35));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("PROMEDIO DE BATEO");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));
        jTextField3.setOpaque(true);
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(35, 35, 35));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 400));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        if (jComboBox1.getSelectedIndex() == 1) {
            this.equipo.ordenarLista();
            this.actualizarTabla(this.equipo.getLista());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaAgregar vista = new VistaAgregar(this, this.equipo);
        vista.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.equipo.getLista().getTamanio() != 0) {
            VistaReportes vista = new VistaReportes(this, equipo);
            vista.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: para acceder a reportes la lista debe tener mas de un elemento");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!(jTextField6.getText().trim().equalsIgnoreCase(""))) {
            Modelo.Nodo nodo = this.equipo.buscarJugador(jTextField6.getText().trim());

            if (nodo != null) {
                javax.swing.JOptionPane.showMessageDialog(this, nodo.getJugador().toString());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,"Error: jugador no encontrado");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Error: debe escribir algo en el campo");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
