/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class VistaHistorial extends javax.swing.JFrame {

    /**
     * Creates new form VistaHistorial
     */
    public VistaHistorial(String[] historialDePrestamos) {
        initComponents();
        
        establecerValoresAInterfaz();
        
        
        //Variable local y estructura repetitiva para agregar el historial al JTextArea
        String textoEnArea = "";
        for(int i = 0;i<historialDePrestamos.length;i++){
            if(historialDePrestamos[i]!=null){
                textoEnArea += historialDePrestamos[i]+"\n";
                jTextArea1.setText(textoEnArea);
            }
        }
    }
    
    public final void establecerValoresAInterfaz() {
        this.getContentPane().setBackground(new java.awt.Color(21, 21, 21));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(21, 21, 21));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("NO SE HAN REALIZADO ACCIONES");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 730, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
