/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class VistaRecibirLibro extends javax.swing.JFrame {

    private Modelo.Biblioteca biblioteca;
    private Modelo.Suscriptor suscriptor;

    public VistaRecibirLibro(Modelo.Biblioteca biblioteca) {
        initComponents();

        this.biblioteca = biblioteca;
        establecerValoresAInterfaz();
    }

    public final void establecerValoresAInterfaz() {
        this.getContentPane().setBackground(new java.awt.Color(21, 21, 21));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolver libro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(35, 35, 35));
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 30));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Codigo de estudiante");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 20, 30));

        jButton1.setBackground(new java.awt.Color(5, 5, 5));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Buscar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 490, 30));

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 3, 3));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 490, 350));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Libros");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 40));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Codigo de libro");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 130, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(35, 35, 35));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setToolTipText("");
        jTextField12.setBorder(null);
        jTextField12.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 220, 30));

        jButton2.setBackground(new java.awt.Color(35, 35, 35));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Devolver");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jPanel1.removeAll();
        jTextField12.setText("");
        if (jTextField1.getText().trim().equals("")) {
            Modelo.metodosComplementarios.mostrarMensaje("Debe escribir el codigo del suscriptor.");
        } else {

            this.suscriptor = biblioteca.getSuscriptor(Integer.valueOf(jTextField1.getText()));

            if (this.suscriptor != null) {
                for (int i = 0; i < suscriptor.getLibros().length; i++) {
                    if (suscriptor.getLibros()[i] != null) {
                        jPanel1.add(new VistaComponenteLibro2(suscriptor.getLibros()[i], jTextField12));
                    }
                }

                for (int i = 0; i < 4; i++) {
                    javax.swing.JPanel panel = new javax.swing.JPanel();
                    panel.setSize(111, 151);
                    panel.setBackground(new java.awt.Color(45, 45, 45));
                    jPanel1.add(panel);
                }
                jPanel1.updateUI();

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.suscriptor == null) {
            Modelo.metodosComplementarios.mostrarMensaje("Debe poner el codigo del suscriptor y buscarlo.");
        } else {
            if (jTextField12.getText().trim().equals("")) {
                Modelo.metodosComplementarios.mostrarMensaje("Debe seleccionar un libro para que se escriba el codigo en el campo del libro.");
            } else {
                this.biblioteca.devolverLibro(Integer.valueOf(jTextField12.getText().trim()), suscriptor);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (!(Character.isDigit(evt.getKeyChar())) || jTextField1.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
