/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jes015
 */
public class VistaPrincipalHorario extends javax.swing.JFrame {

    private Modelo.Horario horario;
    
    private VistaPrincipalHorarioPanelDias[] panelesDias;
    
    private Modelo.Relog Fecha;

    public VistaPrincipalHorario(Modelo.Relog Fecha){
        
        System.gc();
        
        this.horario = new Modelo.Horario();
        
        this.Fecha = Fecha;
        
        this.panelesDias = new VistaPrincipalHorarioPanelDias[Modelo.Horario.dias.length];
        
        try{
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getInstalledLookAndFeels()[0].getClassName());
        }catch(Exception io){
        }
        initComponents();

        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        this.getContentPane().setBackground(new java.awt.Color(10, 13, 23));
        
        this.establecerDiasConActividadesEnInterfaz();
        
    }

    public final void establecerDiasConActividadesEnInterfaz(){
        for(int i =0;i<Modelo.Horario.dias.length;i++){
            panelesDias[i] = new VistaPrincipalHorarioPanelDias(horario.getDias()[i]);
            jPanel1.add(this.panelesDias[i]);
        }
        jPanel1.updateUI();
    }
    
    public final void actualizarJPanelesDeActividadesDeDias(){
        for (VistaPrincipalHorarioPanelDias panelesDia : panelesDias) {
            if (panelesDia != null) {
                panelesDia.actualizarJTextAreaContenedorDeActividades();
            }
        }
    }
    
    public javax.swing.JLabel getLabelHora(){
        return this.jLabel1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        botonEstablecerValorEnDIas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 15));

        jPanel3.setBackground(new java.awt.Color(10, 13, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(291, 67));
        jPanel3.setLayout(new java.awt.BorderLayout());

        botonEstablecerValorEnDIas.setBackground(new java.awt.Color(10, 13, 20));
        botonEstablecerValorEnDIas.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        botonEstablecerValorEnDIas.setForeground(new java.awt.Color(255, 255, 255));
        botonEstablecerValorEnDIas.setText("+");
        botonEstablecerValorEnDIas.setBorder(null);
        botonEstablecerValorEnDIas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstablecerValorEnDIas.setFocusPainted(false);
        botonEstablecerValorEnDIas.setMargin(new java.awt.Insets(2, 90, 2, 90));
        botonEstablecerValorEnDIas.setPreferredSize(new java.awt.Dimension(107, 67));
        botonEstablecerValorEnDIas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerValorEnDIasActionPerformed(evt);
            }
        });
        jPanel3.add(botonEstablecerValorEnDIas, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(5, 5, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(291, 27));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date");
        jPanel2.add(jLabel1, java.awt.BorderLayout.EAST);

        jButton2.setBackground(new java.awt.Color(23, 34, 43));
        jButton2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(244, 232, 193));
        jButton2.setText("Modo Z");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(60, 19));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(10, 13, 20));
        jPanel1.setLayout(new java.awt.GridLayout(0, 5, 12, 12));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEstablecerValorEnDIasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerValorEnDIasActionPerformed
        VistaGestionDeDias ventanaEstablecerActividades = new VistaGestionDeDias(this,this.horario);
        ventanaEstablecerActividades.setVisible(true);
    }//GEN-LAST:event_botonEstablecerValorEnDIasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VistaModoZ vistaModoZ = new VistaModoZ(this.Fecha);
        vistaModoZ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstablecerValorEnDIas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
